name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal

  docker:
    if: github.event_name == 'push'
    needs: build-test
    runs-on: ubuntu-latest

    # 👇 be explicit at job level
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # 🔧 STANDARDIZE: use the SAME name you used locally
      - name: Set image name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/issue-tracker-lite" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # ok to use actor here
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/IssueTrackerLite/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:sha-${{ github.sha }}
